version: "3"
services:
  autotest_api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - autotest_db
    env_file:
      - .env.staging

  autotest_db:
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: autotest