version: "3"
services:
  # cqrs_example_api:
  #   container_name: cqrs_example_api
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #   command: cargo watch -x run
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - autotest_db

  autotest_db:
    container_name: autotest_db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: autotest